### ISSUE TITLE
Upside down issue with player

### ISSUE THREAD

**Issue by Immature29** [stimulant/Cinder-WMFVideo#3]
Hi,
I tried using your code to play movies. Its performance is much better than QuickTime. But facing an issue with the player. The video is getting played but it is inverted(upside down). Tried with many videos but still couldn't find any way.

**Comment by joelpryde** [comment]
Guessing it might due to something related to [this issue](https://forum.libcinder.org/topic/fbo-and-orientation).  I would check to see how you are setting up your viewport matrices.  You should be calling a function like this at some point:

setMatricesWindow (int screenWidth, int screenHeight, bool originUpperLeft=true)

I believe originUpperLeft needs to be set to true.  Hope that helps!

**Comment by LRitesh** [comment]
There's also another fix: setting-

`format.loadTopDown(true);`

in ciWMFVideoPlayer.cpp inside `loadMovie()` where a shared texture is assigned to the video player should fix this.

**Comment by Immature29** [comment]
Thank you @joelpryde  and @LRitesh . Both solutions worked and issue is solved. It really helped.
